[package]
name = "hasher"
version = "0.1.0"
authors = ["bolodev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
rust-crypto = "0.2.36"
time = "0.1.42"
walkdir = "2.3.1"